# 归一化

In [4]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# 原始数据
data = np.array([[1, 200], [2, 300], [3, 400]])

# 使用sklearn的MinMaxScaler进行最小-最大归一化到[0, 1]
scaler = MinMaxScaler(feature_range=(0, 1))
normalized = scaler.fit_transform(data)

print("归一化后的数据:\n", normalized)


归一化后的数据:
 [[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


# 标准化

In [3]:
from sklearn.preprocessing import StandardScaler
import numpy as np
# 原始数据
data = np.array([[1, 200], [2, 300], [3, 400]])

# 使用sklearn的StandardScaler进行标准化
scaler = StandardScaler()
standardized = scaler.fit_transform(data)

print("标准化后的数据:\n", standardized)
print("均值:", scaler.mean_)
print("方差:", scaler.var_)


标准化后的数据:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
均值: [  2. 300.]
方差: [6.66666667e-01 6.66666667e+03]


In [ ]:
#标准化后每列特征均值变为0，方差变为1
import numpy as np
from sklearn.preprocessing import StandardScaler

# 给定的数据
data = np.array([[-1.22474487, -1.22474487],
                 [ 0., 0.],
                 [ 1.22474487, 1.22474487]])

# 对数据进行标准化
scaler = StandardScaler()
standardized = scaler.fit_transform(data)

# print("再次标准化后的数据:\n", standardized)
print("新的均值:", scaler.mean_)
print("新的方差:", scaler.var_)


新的均值: [0. 0.]
新的方差: [1. 1.]


# 缺失值处理

In [8]:
import numpy as np
# 1. 导入缺失值处理的类
from sklearn.impute import SimpleImputer

# 2. 创建数据(包含缺失值)
data = np.array([[1, np.nan], [2, 300], [np.nan, 400]])

# 3. 创建缺失值处理类
# strategy: mean, median, most_frequent, constant
# mean: 使用数据的平均值填充缺失值
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# 4. 训练模型并预测
data_new = imputer.fit_transform(data)

# 5. 输出结果
print(data_new)

[[  1.  350. ]
 [  2.  300. ]
 [  1.5 400. ]]


# 特征选择

In [ ]:
from sklearn.feature_selection import VarianceThreshold

# 创建特征数据
X = np.array([[0, 2, 0, 3],
              [0, 1, 4, 3],
              [0, 1, 1, 3]])

# 初始化方差阈值选择器（默认阈值为0，去除方差为0的特征）
selector = VarianceThreshold(threshold=0.5)

# 拟合并转换数据
X_selected = selector.fit_transform(X)

print("原始数据:\n", X)
print("方差阈值特征选择后的数据:\n", X_selected)
print("保留下来的特征索引:", selector.get_support(indices=True))


原始数据:
 [[0 2 0 3]
 [0 1 4 3]
 [0 1 1 3]]
方差阈值特征选择后的数据:
 [[2 0]
 [1 4]
 [1 1]]
保留下来的特征索引: [1 2]


# PCA 降维

In [14]:
from sklearn.decomposition import PCA

# 创建数据
X = np.array([[0, 2, 0, 3],
              [0, 1, 4, 3],
              [0, 1, 1, 3]])

# 初始化PCA，降到2个主成分
# 0.95表示保留95%的方差
pca = PCA(n_components=0.95)

# 拟合并转换数据
X_pca = pca.fit_transform(X)

print("原始数据:\n", X)
print("PCA降维后的数据:\n", X_pca)
print("解释的方差比:", pca.explained_variance_ratio_)


原始数据:
 [[0 2 0 3]
 [0 1 4 3]
 [0 1 1 3]]
PCA降维后的数据:
 [[-1.76504522]
 [ 2.35339362]
 [-0.58834841]]
解释的方差比: [0.96428571]


In [16]:
import numpy as np

# 计算每一列的方差并求和
col_var_sum = np.sum(np.var(X, axis=0))
col_var_sum


3.111111111111111

In [13]:
import numpy as np

# 定义矩阵
data = np.array([[-1.76504522,  0.32686023],
                 [ 2.35339362,  0.13074409],
                 [-0.58834841, -0.45760432]])

# 计算每一列的方差
col_variances = np.var(data, axis=0, ddof=0)  # 默认分母N，若需样本方差用ddof=1

print("每一列的方差:", col_variances)


每一列的方差: [3.         0.11111111]


In [15]:
import numpy as np

# 定义一维数组
arr = np.array([[-1.76504522],
                [ 2.35339362],
                [-0.58834841]])

# 计算方差
variance = np.var(arr, ddof=0)

print("方差为:", variance)


方差为: 3.0000000036170267
