## 3.1 张量的创建

In [ ]:
# 从数据创建张量

# 导包
import torch

print(torch.__version__)

# 1. 通过标量创建张量
t1 = torch.tensor(1)
print(t1)

# 2. 通过列表创建张量
t2 = torch.tensor([1, 2, 3])
print(t2)

# 3. 通过嵌套列表创建张量
t3 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t3)

# 4. 通过ndarray创建张量
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
t4 = torch.tensor(a)
print(t4)

2.5.1+cu121
tensor(1)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
# 创建特定形状的张量

# 1. 创建全0张量
t5 = torch.zeros(2, 3)
print(t5)

# 2. 创建全1张量
t6 = torch.ones(2, 3)
print(t6)

# 3. 创建指定值的张量
t7 = torch.full((2, 3), 9)
print(t7)

# 4. 创建指定形状的张量, 不推荐，内部的值是原有内存残留
t8 = torch.Tensor(2, 3)
print(t8)

# 5. 创建张量，并指定类型
t9 = torch.empty(2, 3, dtype=torch.int16)
print(t9)

# 6. 创建指定类型的张量
# t10 = torch.FloatTensor(2, 3)   # dtype=torch.float32
# t10 = torch.IntTensor(2, 3)     # dtype=torch.int32
# t10 = torch.LongTensor(2, 3)    # dtype=torch.int64
# t10 = torch.ShortTensor(2, 3)   # dtype=torch.int16
# t10 = torch.BoolTensor(2, 3)    # dtype=torch.bool
t10 = torch.ByteTensor(2, 3)    # dtype=torch.uint8
print(t10)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[9, 9, 9],
        [9, 9, 9]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[6, 0, 0],
        [0, 0, 0]], dtype=torch.int16)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)


In [8]:
# 创建线性张量

# 1. 创建连续整数序列
# torch.arange(start, end, step)
# step 表示步长
t14 = torch.arange(1, 10, 2)
print(t14)

# 2. 创建等差数列
# torch.linspace(start, end, steps)
# steps 表示生成张量的数据个数
t15 = torch.linspace(1, 10, 2)
print(t15)

tensor([1, 3, 5, 7, 9])
tensor([ 1., 10.])


## 3.2 张量的转换

In [ ]:
# 张量类型转换
"""
x.type(torch.float32) 是“通用类型转换接口，可以指定任何 dtype（甚至设备）”；
x.int() 是“专门转成整型的快捷函数，语义更清晰，但不通用”。
"""

# 创建张量
x = torch.randint(0, 10, (2, 3))
print(x)

# 1. 修改张量为指定的数据类型
x = x.type(torch.float32)
print(x)

# 2. 直接修改张量的数据类型
# x = x.int()
# x = x.long()
# x = x.short()
x = x.half()      # 半精度浮点数（16位）
print(x)

tensor([[0, 4, 6],
        [4, 9, 4]])
tensor([[0., 4., 6.],
        [4., 9., 4.]])
tensor([[0., 4., 6.],
        [4., 9., 4.]], dtype=torch.float16)


In [ ]:
# 张量与ndarray的转换

x = torch.randint(0, 10, (2, 3))

# 张量转换为 numpy
x = x.numpy()
print(x)

# 张量转换为列表
x = x.tolist()
print(x)

[[5 3 8]
 [3 9 9]]
[[5, 3, 8], [3, 9, 9]]


## 3.3 张量数值计算

In [ ]:
# 四则运算

a = torch.randint(0, 10, (2, 3), dtype=torch.float)
print(a)

b = torch.randint(0, 10, (2, 3), dtype=torch.float)
print(b)

# 1. 直接与数字进行操作，会对张量进行广播
print("a + 10:", a + 10)
print("a - 10:", a - 10)
print("a * 10:", a * 10)
print("a / 10:", a / 10)

# 2. 张量之间的加减乘除：对应位置相加减乘除（注意：需要形状一致）
print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)

# 3. 使用函数（不改变原张量）
print("a.add(b):", a.add(b))
print("a.sub(b):", a.sub(b))
print("a.mul(b):", a.mul(b))
print("a.div(b):", a.div(b))  # 除法运算，a/b
# print(a)

# 4. 使用函数（改变原张量）
print("a.add_(b):", a.add_(b))
print("a.sub_(b):", a.sub_(b))
print("a.mul_(b):", a.mul_(b))
print("a.div_(b):", a.div_(b))
print(a)

tensor([[4., 6., 3.],
        [0., 1., 5.]])
tensor([[7., 6., 0.],
        [9., 5., 9.]])
a + 10: tensor([[14., 16., 13.],
        [10., 11., 15.]])
a - 10: tensor([[ -6.,  -4.,  -7.],
        [-10.,  -9.,  -5.]])
a * 10: tensor([[40., 60., 30.],
        [ 0., 10., 50.]])
a / 10: tensor([[0.4000, 0.6000, 0.3000],
        [0.0000, 0.1000, 0.5000]])
a + b: tensor([[11., 12.,  3.],
        [ 9.,  6., 14.]])
a - b: tensor([[-3.,  0.,  3.],
        [-9., -4., -4.]])
a * b: tensor([[28., 36.,  0.],
        [ 0.,  5., 45.]])
a / b: tensor([[0.5714, 1.0000,    inf],
        [0.0000, 0.2000, 0.5556]])
a.add(b): tensor([[11., 12.,  3.],
        [ 9.,  6., 14.]])
a.sub(b): tensor([[-3.,  0.,  3.],
        [-9., -4., -4.]])
a.mul(b): tensor([[28., 36.,  0.],
        [ 0.,  5., 45.]])
a.div(b): tensor([[0.5714, 1.0000,    inf],
        [0.0000, 0.2000, 0.5556]])
a.add_(b): tensor([[11., 12.,  3.],
        [ 9.,  6., 14.]])
a.sub_(b): tensor([[4., 6., 3.],
        [0., 1., 5.]])
a.mul_(b): tensor([[

In [13]:
# 其他数学操作

a = torch.randint(0, 10, (2, 3), dtype=torch.float)
print(a)

# 1. 取负
print("-a:", -a)
print("a.neg():", a.neg())

print("a.neg_():", a.neg_())

# 2. 求幂
print("a**2:", a**2)
print("a.pow(2):", a.pow(2))
print("a.pow_(2):", a.pow_(2))

# 3. 求平方根
print("a.sqrt():", a.sqrt())
print("a.sqrt_():", a.sqrt_())

# 4. 求 e 为底的指数
print("a.exp():", a.exp())
print("a.exp_():", a.exp_())

# 5. 求 e 为底的对数
print("a.log():", a.log())
print("a.log_():", a.log_())

# 6. 矩阵乘法
a = torch.randint(0, 10, (2, 3))
b = torch.randint(0, 10, (3, 2))
print("a.mm(b):", a.mm(b))          # 只支持 2 维张量
print("a.matmul(b):", a.matmul(b))  # 支持任意维度张量
print("a @ b:", a @ b)              # 支持任意维度张量

tensor([[5., 2., 1.],
        [6., 6., 3.]])
-a: tensor([[-5., -2., -1.],
        [-6., -6., -3.]])
a.neg(): tensor([[-5., -2., -1.],
        [-6., -6., -3.]])
a.neg_(): tensor([[-5., -2., -1.],
        [-6., -6., -3.]])
a**2: tensor([[25.,  4.,  1.],
        [36., 36.,  9.]])
a.pow(2): tensor([[25.,  4.,  1.],
        [36., 36.,  9.]])
a.pow_(2): tensor([[25.,  4.,  1.],
        [36., 36.,  9.]])
a.sqrt(): tensor([[5., 2., 1.],
        [6., 6., 3.]])
a.sqrt_(): tensor([[5., 2., 1.],
        [6., 6., 3.]])
a.exp(): tensor([[148.4132,   7.3891,   2.7183],
        [403.4288, 403.4288,  20.0855]])
a.exp_(): tensor([[148.4132,   7.3891,   2.7183],
        [403.4288, 403.4288,  20.0855]])
a.log(): tensor([[5.0000, 2.0000, 1.0000],
        [6.0000, 6.0000, 3.0000]])
a.log_(): tensor([[5.0000, 2.0000, 1.0000],
        [6.0000, 6.0000, 3.0000]])
a.mm(b): tensor([[58, 89],
        [66, 45]])
a.matmul(b): tensor([[58, 89],
        [66, 45]])
a @ b: tensor([[58, 89],
        [66, 45]])


## 3.4 张量的运算函数

In [ ]:
a = torch.randint(0, 10, (2, 3), dtype=torch.float)
print("a:", a)

# 1. 求和 sum
print("sum:", a.sum())

# 2. 求和，指定维度
print("sum-dim:", a.sum(dim=0))

# 3. 求均值
print("mean:", a.mean())
print("mean-dim:", a.mean(dim=1))

# 4. 求最大值
print("max:", a.max())
print("max-dim:", a.max(dim=0))

# 5. 求最小值
print("min:", a.min())
print("min-dim:", a.min(dim=1))

# 6. 求最大值索引
print("argmax:", a.argmax())  # 此处未指定dim，返回的是a展平后的最大值索引
print("argmax-dim:", a.argmax(dim=1))

# 7. 求最小值索引
print("argmin:", a.argmin())
print("argmin-dim:", a.argmin(dim=1))

# 8. 求标准差
print("std:", a.std())
print("std-dim:", a.std(dim=1))

# 9. 求方差
print("var:", a.var())
print("var-dim:", a.var(dim=1))

# 10. 去重
print("unique:", a.unique())

# 11. 排序
print("sort:", a.sort())
print("sort-dim:", a.sort(dim=0))

a: tensor([[9., 3., 7.],
        [3., 6., 6.]])
sum: tensor(34.)
sum-dim: tensor([12.,  9., 13.])
mean: tensor(5.6667)
mean-dim: tensor([6.3333, 5.0000])
max: tensor(9.)
max-dim: torch.return_types.max(
values=tensor([9., 6., 7.]),
indices=tensor([0, 1, 0]))
min: tensor(3.)
min-dim: torch.return_types.min(
values=tensor([3., 3.]),
indices=tensor([1, 0]))
argmax: tensor(0)
argmax-dim: tensor([0, 1])
argmin: tensor(1)
argmin-dim: tensor([1, 0])
std: tensor(2.3381)
std-dim: tensor([3.0551, 1.7321])
var: tensor(5.4667)
var-dim: tensor([9.3333, 3.0000])
unique: tensor([3., 6., 7., 9.])
sort: torch.return_types.sort(
values=tensor([[3., 7., 9.],
        [3., 6., 6.]]),
indices=tensor([[1, 2, 0],
        [0, 1, 2]]))
sort-dim: torch.return_types.sort(
values=tensor([[3., 3., 6.],
        [9., 6., 7.]]),
indices=tensor([[1, 0, 1],
        [0, 1, 0]]))


## 3.5 张量的索引

In [16]:
torch.manual_seed(22)
# 张量的索引操作
x = torch.randint(0, 10, (4, 5))
print("原始张量 x:\n", x)

# 1. 行索引
print("第一行 x[0]:\n", x[0])         
print("前两行 x[0:2]:\n", x[0:2])       

# 2. 列索引
print("第一列 x[:, 0]:\n", x[:, 0])      
print("前两列 x[:, 0:2]:\n", x[:, 0:2])    

# 3. 列表索引
print("x[[0, 1], [0, 1]]，返回(0,0)和(1,1)两个元素:\n", x[[0, 1], [0, 1]])        
print("x[[0, 1], :]，返回第0行和第1行:\n", x[[0, 1], :])             

# 4. 范围索引
print("x[1:3, 1:3]，返回第1~2行和第1~2列:\n", x[1:3, 1:3])              

# 5. 布尔索引
# 返回所有大于5的元素
print("所有大于5的元素 x[x > 5]:\n", x[x > 5])

# 返回第二行大于5的元素
print("第二行大于5的元素 x[1, x[1] > 5]:\n", x[1, x[1] > 5])

# 返回第二列大于5的元素
print("第二列大于5的元素 x[:, 1][x[:, 1] > 5]:\n", x[:, 1][x[:, 1] > 5])

# 6. 多维索引
x = torch.randint(0, 10, (3, 4, 5))
print("三维张量 x:\n", x)

# 获取第0轴的第一个元素
print("第0轴的第一个元素 x[0, :, :]:\n", x[0, :, :])

# 获取第1轴的第一个元素
print("第1轴的第一个元素 x[:, 0, :]:\n", x[:, 0, :])

# 获取第2轴的第一个元素
print("第2轴的第一个元素 x[:, :, 0]:\n", x[:, :, 0])

原始张量 x:
 tensor([[9, 6, 6, 4, 2],
        [2, 2, 1, 8, 0],
        [1, 0, 3, 2, 4],
        [4, 9, 0, 0, 1]])
第一行 x[0]:
 tensor([9, 6, 6, 4, 2])
前两行 x[0:2]:
 tensor([[9, 6, 6, 4, 2],
        [2, 2, 1, 8, 0]])
第一列 x[:, 0]:
 tensor([9, 2, 1, 4])
前两列 x[:, 0:2]:
 tensor([[9, 6],
        [2, 2],
        [1, 0],
        [4, 9]])
x[[0, 1], [0, 1]]，返回(0,0)和(1,1)两个元素:
 tensor([9, 2])
x[[0, 1], :]，返回第0行和第1行:
 tensor([[9, 6, 6, 4, 2],
        [2, 2, 1, 8, 0]])
x[1:3, 1:3]，返回第1~2行和第1~2列:
 tensor([[2, 1],
        [0, 3]])
所有大于5的元素 x[x > 5]:
 tensor([9, 6, 6, 8, 9])
第二行大于5的元素 x[1, x[1] > 5]:
 tensor([8])
第二列大于5的元素 x[:, 1][x[:, 1] > 5]:
 tensor([6, 9])
三维张量 x:
 tensor([[[3, 2, 9, 7, 8],
         [4, 1, 7, 9, 6],
         [8, 1, 6, 1, 0],
         [3, 5, 3, 8, 5]],

        [[7, 7, 5, 1, 8],
         [8, 9, 5, 5, 2],
         [9, 0, 5, 6, 7],
         [9, 1, 3, 7, 5]],

        [[1, 7, 4, 9, 0],
         [0, 5, 1, 7, 3],
         [9, 7, 6, 5, 7],
         [9, 0, 7, 0, 1]]])
第0轴的第一个元素 x[0, :, :]:
 tens

## 3.6 张量形状操作

In [ ]:
x = torch.randn(2, 3, 4)
print("原始张量形状:\n", x.shape)
print("使用size()方法获取形状:\n", x.size())         # size() 方法和 shape 一样, 返回张量的形状

# 1. 调整形状
x = x.reshape(2, 12)            # 调整为2行12列
print("reshape后变为(2,12)的形状: x.shape1:\n", x.shape)
x = x.reshape(-1, 3)            # 不限制行数, 列数调整为3列 (会自动计算行数)
print("reshape(-1, 3)后, 自动计算行数: x.shape2:\n", x.shape)

# 2. 交换维度
x = torch.randn(2, 3, 4)
x = x.transpose(1, 2)
print("transpose(1, 2)后, 交换第1与第2维: x.shape:\n", x.shape)

# 3. 重新排列多个维度
# 第3维度变为第1维, 第2维变为第2维, 第1维变为第3维
x = x.permute(2, 1, 0)
print("permute(2, 1, 0)后, 维度顺序变为(2, 1, 0): x.shape:\n", x.shape)

# 4. 在指定维度上增加一个维度, 会添加形状为1的维度
x = x.unsqueeze(dim=2)
print("unsqueeze(dim=2)后, 在第2个轴增加一个维度: x.shape:\n", x.shape)

# 5. 在指定维度上删除一个维度, 会删除形状为1的维度 (如果该维度不存在形状为1的维度, 则返回原张量)
x = x.squeeze(dim=1)
print("squeeze(dim=1)后, 删除形状为1的第1个轴: x.shape:\n", x.shape)

# 6. 调整形状, 需要连续内存
# 经过升维和降维操作, 张量的数据存储位置 (内存) 可能会改变, 所以内存可能不连续
# 使用view方法, 如果内存不连续, 那么会报错
# x = x.view(3,-1)
# print(x)

# 6. 判断是否是连续内存
print("当前x是否为连续内存:\n", x.is_contiguous())

# 7. 转换为连续内存
x = x.contiguous()
print("调用contiguous()后, x现在是否为连续内存:\n", x.is_contiguous())

# 8. 调整形状, 需要连续内存
x = x.view(3, -1)
print("view(3, -1)后的形状: x.shape:\n", x.shape)

原始张量形状:
 torch.Size([2, 3, 4])
使用size()方法获取形状:
 torch.Size([2, 3, 4])
reshape后变为(2,12)的形状: x.shape1:
 torch.Size([2, 12])
reshape(-1, 3)后, 自动计算行数: x.shape2:
 torch.Size([8, 3])
transpose(1, 2)后, 交换第1与第2维: x.shape:
 torch.Size([2, 4, 3])
permute(2, 1, 0)后, 维度顺序变为(2, 1, 0): x.shape:
 torch.Size([3, 4, 2])
unsqueeze(dim=2)后, 在第2个轴增加一个维度: x.shape:
 torch.Size([3, 4, 1, 2])
squeeze(dim=1)后, 删除形状为1的第1个轴: x.shape:
 torch.Size([3, 4, 1, 2])
当前x是否为连续内存:
 False
调用contiguous()后, x现在是否为连续内存:
 True
view(3, -1)后的形状: x.shape:
 torch.Size([3, 8])


## 3.7 张量的拼接

In [20]:
import torch

# 创建两个张量
x = torch.rand(2, 3, 4)
y = torch.rand(4, 3, 4)

# 1. cat() 按照指定维度进行拼接
# x和y, 除了0轴维度不一样, 其他轴维度相同
z = torch.cat([x, y], dim=0)
print(z.shape)              # 结果是[6,3,4]

# z = torch.cat([x, y], dim=1)    # 会报错, 因为x和y只有0轴不同, 其他轴维度相同, 只能拼接0轴

# 2. 按照新维度堆叠 (堆叠的张量, 必须形状一致, 不然会报错)
# z = torch.stack([x, y], dim=3)

x = torch.rand(2, 3, 4)
y = torch.rand(2, 3, 4)

z = torch.stack([x, y], dim=2)        # dim是2, z的维度是[2,3,2,4]
print(z.shape)

torch.Size([6, 3, 4])
torch.Size([2, 3, 2, 4])


## 3.8 自动微分

In [21]:
import torch

# 1. 准备数据：参数与目标值
x = torch.tensor(5) #特征
y = torch.tensor(0.)

# 2. 初始化参数：权重与偏置
w = torch.tensor(1., requires_grad=True, dtype=torch.float32)
b = torch.tensor(3., requires_grad=True, dtype=torch.float32)

# 3. 构建神经网络并输出值
z = w * x + b

# 4. 计算损失
loss = torch.nn.MSELoss()
loss = loss(z, y)

# 5. 反向传播，自动微分，计算梯度
loss.backward()

# 6. 访问梯度
print(w.grad)
print(b.grad)

tensor(80.)
tensor(16.)


In [22]:
import torch

# 1. 准备数据：参数与目标值
x = torch.ones(2,5)
y = torch.zeros(2,3)

# 2. 初始化参数：权重与偏置
w = torch.randn(5,3, requires_grad=True)
b = torch.randn(3,requires_grad=True,)

# 3. 构建神经网络并输出值
z = torch.matmul(x, w) + b

# 4. 计算损失
loss = torch.nn.MSELoss()
loss = loss(z, y)

# 5. 反向传播，自动微分，计算梯度
loss.backward()

# 6. 访问梯度
print(w.grad)
print(b.grad)

tensor([[-1.9665,  0.0936,  1.1125],
        [-1.9665,  0.0936,  1.1125],
        [-1.9665,  0.0936,  1.1125],
        [-1.9665,  0.0936,  1.1125],
        [-1.9665,  0.0936,  1.1125]])
tensor([-1.9665,  0.0936,  1.1125])
