# 默写缺失值的处理过程

In [3]:

import pandas as pd
import numpy as np

# 假设有一个示例 DataFrame
data = {
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8],
    'C': [10, 11, 12, 13]
}
df = pd.DataFrame(data)
print(df)

# 1. 查看缺失值情况
print("各列缺失值数量：")
print(df.isnull().sum())

# 2. 删除含有缺失值的行
df_dropna = df.dropna()
print("\n删除含有缺失值的行后：")
print(df_dropna)

# 3. 用指定值填充缺失值
df_fillna = df.fillna(0)
print("\n用0填充缺失值后：")
print(df_fillna)

# 4. 用均值或中位数等统计量填充缺失值
df_fillmean = df.fillna(df.mean())
print("\n用均值填充缺失值后：")
print(df_fillmean)


     A    B   C
0  1.0  5.0  10
1  2.0  NaN  11
2  NaN  NaN  12
3  4.0  8.0  13
各列缺失值数量：
A    1
B    2
C    0
dtype: int64

删除含有缺失值的行后：
     A    B   C
0  1.0  5.0  10
3  4.0  8.0  13

用0填充缺失值后：
     A    B   C
0  1.0  5.0  10
1  2.0  0.0  11
2  0.0  0.0  12
3  4.0  8.0  13

用均值填充缺失值后：
          A    B   C
0  1.000000  5.0  10
1  2.000000  6.5  11
2  2.333333  6.5  12
3  4.000000  8.0  13


# 完成鸢尾花，20类新闻数据集的加载及理解

In [7]:
from sklearn import datasets
import pandas as pd

# 加载鸢尾花数据集
iris = datasets.load_iris()

# 查看数据集的基本信息
print("特征名称：", iris.feature_names)
print("目标名称：", iris.target_names)

# 构建DataFrame
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target

# 查看前5行数据
print(iris_df.head())

# 查看每一类样本数量
print("\n每一类样本数量：")
print(iris_df['target'].value_counts())

# 描述性统计
print("\n描述性统计：")
print(iris_df.describe())


特征名称： ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
目标名称： ['setosa' 'versicolor' 'virginica']
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  

每一类样本数量：
target
0    50
1    50
2    50
Name: count, dtype: int64

描述性统计：
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866          

In [11]:
from sklearn.datasets import fetch_20newsgroups

# 加载20类新闻数据集
newsgroups = fetch_20newsgroups(subset='all')

# 查看20类新闻数据集的基本信息
print("类别数：", len(newsgroups.target_names))
print("类别名称：", newsgroups.target_names)
print("新闻样本数量：", len(newsgroups.data))

# 输出前2个文本样本和对应类别
for i in range(2):
    print(f"\n第{i+1}条新闻样本文本：\n", newsgroups.data[i][:300], "...")  # 打印前300字符
    print("对应的类别：", newsgroups.target_names[newsgroups.target[i]])


类别数： 20
类别名称： ['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']
新闻样本数量： 18846

第1条新闻样本文本：
 From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>
Subject: Pens fans reactions
Organization: Post Office, Carnegie Mellon, Pittsburgh, PA
Lines: 12
NNTP-Posting-Host: po4.andrew.cmu.edu



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent ...
对应的类别： rec.sport.hockey

第2条新闻样本文本：
 From: mblawson@midway.ecn.uoknor.edu (Matthew B Lawson)
Subject: Which high-performance VLB video card?
Summary: Seek recommendations for VLB video card
Nntp-Posting-Host: midway.ecn.uoknor.edu
Organization: Engineering Com

# 机器学习的DictVectorizer练习，CountVectorizer, TfidfVectorizer练习

In [17]:
from sklearn.feature_extraction import DictVectorizer

data = [
    {'颜色': '红', '尺寸': '大', '价格': 100},
    {'颜色': '蓝', '尺寸': '中', '价格': 80},
    {'颜色': '红', '尺寸': '小', '价格': 50}
]
vcs=DictVectorizer()
vcs.fit_transform(data).toarray()
data_vcs=vcs.fit_transform(data).toarray()
print(vcs.get_feature_names_out())
print(data_vcs)


from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "I love machine learning. Machine learning is interesting.",
    "I love coding. Coding is fun and useful.",
    "Machine learning and coding are my favorite skills."
]
# 创建CountVectorizer对象
cv=CountVectorizer()
cv.fit_transform(documents).toarray()
data_cv=cv.fit_transform(documents).toarray()
print(cv.get_feature_names_out())
print(data_cv)

from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "人生苦短，我喜欢 python", 
    "人生漫长，不用 python python",
    "人生漫漫，不用 python python python"
]
# 创建TfidfVectorizer对象
tf = TfidfVectorizer()
tf.fit_transform(documents).toarray()
data_tf=tf.fit_transform(documents).toarray()
print(tf.get_feature_names_out())
print(data_tf)






['价格' '尺寸=中' '尺寸=大' '尺寸=小' '颜色=红' '颜色=蓝']
[[100.   0.   1.   0.   1.   0.]
 [ 80.   1.   0.   0.   0.   1.]
 [ 50.   0.   0.   1.   1.   0.]]
['and' 'are' 'coding' 'favorite' 'fun' 'interesting' 'is' 'learning'
 'love' 'machine' 'my' 'skills' 'useful']
[[0 0 0 0 0 1 1 2 1 2 0 0 0]
 [1 0 2 0 1 0 1 0 1 0 0 0 1]
 [1 1 1 1 0 0 0 1 0 1 1 1 0]]
['python' '不用' '人生漫漫' '人生漫长' '人生苦短' '我喜欢']
[[0.38537163 0.         0.         0.         0.65249088 0.65249088]
 [0.68499287 0.44102652 0.         0.57989687 0.         0.        ]
 [0.81574546 0.35014027 0.46039237 0.         0.         0.        ]]
