In [4]:
import time

time.time() # 当前时间戳，单位秒，1970年1月1日0时0分0秒开始

1771811068.9077847

In [6]:
# 编写zip例子
# zip的功能是创建一个迭代器，迭代器中包含两个列表的元素，两个列表的元素一一对应。
list1 = [1, 2, 3]
list2 = [4,5,6]
list(zip(list1, list2))

[(1, 4), (2, 5), (3, 6)]

In [8]:
[1,2,3]+[1,2,3]

[1, 2, 3, 1, 2, 3]

In [10]:
import numpy as np
import time

# 列表处理1000万个数字的加法（慢，需循环）
start = time.time()
list1 = [i for i in range(10000000)]
list2 = [i*2 for i in range(10000000)]
result = [a + b for a, b in zip(list1, list2)]  # 需循环
end = time.time()
print(f"列表处理1000万个数字的加法耗时：{end-start}")

# NumPy数组处理（快，直接运算）
arr1 = np.arange(10000000)
arr2 = np.arange(10000000) * 2
result = arr1 + arr2  # 无需循环，直接矢量化运算
time3 = time.time()
print(f"NumPy数组处理1000万个数字的加法耗时：{time3-end}")

列表处理1000万个数字的加法耗时：1.133117437362671
NumPy数组处理1000万个数字的加法耗时：0.080718994140625


# 创建ndarray

In [11]:
import numpy as np

# 创建一个一维ndarray
arr1 = np.array([1, 2, 3])
print(arr1)
print(type(arr1))

# 创建一个二维ndarray
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(type(arr2))

# 创建一个三维ndarray
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3)
print(type(arr3))

[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


In [16]:
np.zeros((2))  				# 创建一个2行3列全0数组


array([0., 0.])

In [13]:
np.ones((3, 2))   			# 创建一个3行2列全1数组

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.empty((2,3))				# 创建一个2行3列，元素值内容随机且依赖于内存状态的数组

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# 创建一个一维数组，起始值0，结束值10，步长2，元素类型:float32
# 左闭右开
arr4 = np.arange(0, 10, 2, dtype=np.float32)
arr4

array([0., 2., 4., 6., 8.], dtype=float32)

In [21]:
arr4 = np.matrix([[1, 2, 3], [4, 5, 6]])
arr4

matrix([[1, 2, 3],
        [4, 5, 6]])

In [22]:
# 1. 创建一个0-1的随机数矩阵, 矩阵是2行3列
arr5 = np.random.random((2,3))
print(arr5)
print(type(arr5))

# 2. 创建一个0-10的随机整数矩阵, 矩阵是2行3列
arr6 = np.random.randint(0, 10, (2,3))
print(arr6)
print(type(arr6))

# 3. 创建一个0-10的随机浮点数矩阵, 矩阵是2行3列，是均匀分布
arr7 = np.random.uniform(0, 10, (2,3))
print(arr7)
print(type(arr7))

[[0.98477579 0.73286563 0.60612896]
 [0.5879571  0.74270208 0.77100674]]
<class 'numpy.ndarray'>
[[5 1 8]
 [4 8 3]]
<class 'numpy.ndarray'>
[[0.80665322 9.06712421 1.75322614]
 [1.95839199 5.71298166 0.19523869]]
<class 'numpy.ndarray'>


# ndarray属性

In [25]:
# 创建一个2行3列的矩阵、
arr8 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr8)
print(arr8.shape)   # 形状（行数, 列数）→ (2, 3)
print(arr8.ndim)    # 维度 → 2（二维数组）
print(arr8.dtype)   # 数据类型 → int64（默认）
print(arr8.size)    # 总元素数 → 6

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32
6


In [26]:
# 创建一个3维数组

arr9 = np.arange(24).reshape(2, 3, 4)
print(arr9) 
print(arr9.shape) # 形状（0轴,1轴，2轴）
print(arr9.ndim)
print(arr9.dtype)
print(arr9.size)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3
int32
24


# 4.1 形状改变

In [27]:
# 一维变多维
arr9 = np.arange(0, 12)
arr10 = arr9.reshape(3,4)

# 说明: 不改变原有矩阵，返回改变之后的新矩阵
print(arr9)
print(arr10)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开,不重要，用不上
arr15 = arr10.reshape((12,),order='F')
print(arr15)

[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [32]:
arr11=arr10+2
print(arr11)
arr12=arr11.reshape(12)  #再变回一维，元素位置不变
print(arr12)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[ 2  3  4  5  6  7  8  9 10 11 12 13]


# 4.2 类型转换

In [34]:
# astype(), 转换ndarray的类型
arr12 = np.array([1, 2, 3, 4, 5, 6])
print(arr12.dtype)
print(arr12)
arr13 = arr12.astype(np.float32)		# 转为浮点型 → [1. 2. 3. 4. 5. 6.]
print(arr13.dtype)
print(arr13)

int32
[1 2 3 4 5 6]
float32
[1. 2. 3. 4. 5. 6.]


# 4.3 索引与切片

In [36]:
# 1. 列表的索引与切片
# list[start:end:step]
arr = [1, 2, 3, 4, 5, 6]
print(arr[0:4:2])           # 1,3

# 2. 一维ndarray的索引与切片， 和列表的索引与切片一样
arr14 = np.arange(0, 12)
print(arr14[0:4:2])         # [0,2]

print('-'*50)
# 3. 多维ndarray的索引与切片
arr15 = np.arange(0, 12).reshape(3,4)
print(arr15)

# 取一行(下标为1的一行, 也就是第二行)
print(arr15[1,:])

# 取一列(下标为1的一列, 也就是第二列)
print(arr15[:,1])

# 取不连续的多行
print(arr15[[0,2],:])

# 取从第2行开始的所有行
print(arr15[1:,:])

[1, 3]
[0 2]
--------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
[1 5 9]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]


In [45]:
arr16 = np.arange(0, 24).reshape(2,3,4)
print(arr16)
print('-'*50)
print(arr16[1,:])
print('-'*50)
print(arr16[1,:,:])
print('-'*50)
print(arr16[:,1])
print('-'*50)
print(arr16[:,[0,2],:])
print('-'*50)
print(arr16[:,:,2:])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------------------------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------------------------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------------------------------------
[[ 4  5  6  7]
 [16 17 18 19]]
--------------------------------------------------
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [20 21 22 23]]]
--------------------------------------------------
[[[ 2  3]
  [ 6  7]
  [10 11]]

 [[14 15]
  [18 19]
  [22 23]]]


# 4.4 元素的修改

In [3]:
import numpy as np
arr15 = np.arange(0, 12).reshape(3,4)
print(arr15)
arr15[[1,2],[0,3]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 4, 11])

In [54]:
arr15 = np.arange(0, 12).reshape(3,4)
arr15>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
# 元素修改
arr15 = np.arange(0, 12).reshape(3,4)

print(arr15)
# 修改单个值
arr15[1,1] = 100
print(arr15)
print('-'*50)
arr15 = np.arange(0, 12).reshape(3,4)
# 修改某一行的值
arr15[1,:] = 100
print(arr15)
print('-'*50)
# 修改某一列的值
arr15[:,1] = 100
print(arr15)
print('-'*50)
arr15 = np.arange(0, 12).reshape(3,4)
# 修改某一个块的值
arr15[0:2,0:2] = 100
print(arr15)
print('-'*50)
# 修改多个不相邻的点 (0,0) (1,1) (2,3)
arr15[[0,1,2],[0,1,3]] = 99
print(arr15)
print('-'*50)
# 根据条件修改
arr15 = np.arange(0, 12).reshape(3,4)
arr15[arr15>5] = 0
print(arr15)
print('-'*50)
# 三目运算
result = np.where(arr15>0,10,20)
print(result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   2   3]
 [  4 100   6   7]
 [  8   9  10  11]]
--------------------------------------------------
[[  0   1   2   3]
 [100 100 100 100]
 [  8   9  10  11]]
--------------------------------------------------
[[  0 100   2   3]
 [100 100 100 100]
 [  8 100  10  11]]
--------------------------------------------------
[[100 100   2   3]
 [100 100   6   7]
 [  8   9  10  11]]
--------------------------------------------------
[[ 99 100   2   3]
 [100  99   6   7]
 [  8   9  10  99]]
--------------------------------------------------
[[0 1 2 3]
 [4 5 0 0]
 [0 0 0 0]]
--------------------------------------------------
[[20 10 10 10]
 [10 10 20 20]
 [20 20 20 20]]


# 5 数组的运算

In [58]:
arr16 = np.arange(0, 12).reshape(3,4)
print(arr16)
print('-' * 20)
print(arr16 + 10) # 加法，有广播机制，每一个元素都加上10
print('-'*20)
print(arr16 - 5)
print('-'*20)
print(arr16 * 2)
print('-'*20)
print(arr16 / 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
--------------------
[[-5 -4 -3 -2]
 [-1  0  1  2]
 [ 3  4  5  6]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
--------------------
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [60]:
# 1. 同种形状的矩阵运算，运算结果是按对应位置 进行运算
arr17 = np.arange(10, 22).reshape(3,4)
print(arr17)
arr18 = np.arange(1, 13).reshape(3,4)
print(arr18)

# 加法
print('-'*50)
print(arr17 + arr18)
# 减法
print('-'*50)
print(arr17 - arr18)
# 乘法
print('-'*50)
print(arr17 * arr18)
# 除法
print('-'*50)
print(arr17 / arr18)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------------------------------
[[11 13 15 17]
 [19 21 23 25]
 [27 29 31 33]]
--------------------------------------------------
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
--------------------------------------------------
[[ 10  22  36  52]
 [ 70  90 112 136]
 [162 190 220 252]]
--------------------------------------------------
[[10.          5.5         4.          3.25      ]
 [ 2.8         2.5         2.28571429  2.125     ]
 [ 2.          1.9         1.81818182  1.75      ]]


In [61]:
#不同形状的，运算出错
arr19 = np.arange(0, 12).reshape(3,4)
arr20 = np.arange(0, 4).reshape(2,2)
# print(arr19 + arr20)

ValueError: operands could not be broadcast together with shapes (3,4) (2,2) 

# 当两个数组形状不同时，其中一个数组的列数或行数必须为1，广播运算。如果是3维及以上的，依然是这个规律

In [64]:

# 列数相同（行形状相同）
arr21 = np.arange(0, 12).reshape(3,4)       # 3行4列
print(arr21)
arr22 = np.arange(0, 4).reshape(1,4)                
print(arr22)

# 依然是广播的特性
print(arr22-arr21)


print('-'*50)
# 行数相同（列形状相同）
arr23 = np.arange(0, 12).reshape(3,4)
print(arr23)
arr24 = np.arange(0, 3).reshape(3,1)
print(arr24)
# 依然是广播的特性
print(arr23-arr24)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[[ 0  0  0  0]
 [-4 -4 -4 -4]
 [-8 -8 -8 -8]]
--------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [1]
 [2]]
[[0 1 2 3]
 [3 4 5 6]
 [6 7 8 9]]


In [65]:
#产生2个3维的数组
arr25 = np.arange(0, 24).reshape(2,3,4)
arr26 = np.arange(0, 8).reshape(2,1,4)
result=arr25+arr26
print(result.shape)

(2, 3, 4)


In [72]:

arr25 = np.arange(0, 24).reshape(2,3,4)
arr26 = np.arange(0, 2).reshape(2,1,1)
# print(arr25)
# print(arr26)
result=arr25+arr26
print(result.shape)

(2, 3, 4)


In [73]:
arr25 = np.arange(0, 6).reshape(2,3,1)
arr26 = np.arange(0, 8).reshape(2,1,4)
result=arr25+arr26
print(result.shape) #无需看每个元素的值，把握形状即可

(2, 3, 4)
