# 6.2 常用统计函数

### 规律：按哪一个轴进行运算，对应的轴就会发生改变

In [25]:
import numpy as np
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)

# 求所有数据的和
print(arr25.sum())

# 按轴求和
# axis = 0, 表示按列求和
print(arr25.sum(axis=0))

# axis=1, 表示按行求和
print(arr25.sum(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
[15 18 21 24]
[10 26 42]


In [26]:
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)
# 1. 求所有数的平均值
print(arr25.mean())

# 2. 按轴求平均值
# axis = 0, 按列求平均值
print(arr25.mean(axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
6.5
[5. 6. 7. 8.]


In [27]:
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)

# 1. 求所有数的最大值
print(arr25.max())

# 2. 按轴求最大值
# axis = 0, 按列求最大值
print(arr25.max(axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[ 9 10 11 12]


In [28]:
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)

# 1. 求所有数的前缀和，不写轴会被展平，就是变为1维
print(arr25.cumsum())

# 2. 按轴求前缀和
# axis = 1, 按行求前缀和
print(arr25.cumsum(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  3  6 10 15 21 28 36 45 55 66 78]
[[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]]


In [29]:
arr25 = np.random.randint(0, 100, (3, 4))
print(arr25)

# 1. 求所有数的最小值索引
print(arr25.argmin())
# 2. 按轴求最小值索引
# axis = 1, 按行求最小值索引
print(arr25.argmin(axis=1))

[[ 3 37 81 56]
 [17 37 29 31]
 [ 9 24 79 95]]
0
[0 0 0]


In [30]:
arr25 = np.arange(1, 13).reshape(3, 4)
print(arr25)

# 1. 求所有数的标准差
print(arr25.std())

# 2. 按轴求标准差
# axis = 1, 按行求标准差
print(arr25.std(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3.452052529534663
[1.11803399 1.11803399 1.11803399]


# 7.1 数组的添加

In [31]:
arr27 = np.array([[1,2,3],[4,5,6]])
print(arr27)

# 数组的添加
# 1. 默认情况下，展开为一维数组再添加
arr28 = np.append(arr27, np.array([7,8,9]))
print(arr28)

# 2. 指定轴添加
# axis = 0, 沿着0轴添加元素
arr29 = np.append(arr27, np.array([[7,8,9]]), axis=0)
print(arr29)

# axis=1, 沿着1轴添加元素
arr30 = np.append(arr27, np.array([[7],[8]]), axis=1)
print(arr30)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 7]
 [4 5 6 8]]


In [32]:
#7.2 数组的删除
arr28 = np.array([[1,2,3],[4,5,6]])
print(arr28)

# 1. 默认情况下，展开为一维数组再删除, 2表示删除索引为2的元素
arr31 = np.delete(arr28, 2)
print(arr31)
print('-'*20)

# 2. 指定轴删除
# axis = 0, 沿着0轴删除元素
# 0表示删除索引为0的元素, 也就是删除第一行
arr32 = np.delete(arr28, 0, axis=0)
print(arr32)

[[1 2 3]
 [4 5 6]]
[1 2 4 5 6]
--------------------
[[4 5 6]]


In [33]:
#7.3 数组的去重
arr29 = np.array([1,2,3,4,5,5,5,6,7,8,9,9]).reshape(3,4)
print(arr29)

# 1. 直接去重
# 默认情况下，展开一维数组再去重，得到的也是一维数组
arr30 = np.unique(arr29)
print(arr30)

# 2. 按轴去重
# axis = 0, 沿着0轴去重
# 添加一行重复数据
arr31 = np.append(arr29, np.array([[1,2,3,4]]), axis=0)
print(arr31)

# 去重，去除重复数据
arr32 = np.unique(arr31, axis=0)
print(arr32)

[[1 2 3 4]
 [5 5 5 6]
 [7 8 9 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4]
 [5 5 5 6]
 [7 8 9 9]
 [1 2 3 4]]
[[1 2 3 4]
 [5 5 5 6]
 [7 8 9 9]]


# 7.4 数组的拼接与分割

In [34]:
# 数组的拼接，非拼接轴，对应的size必须一致  不会增加维度
arr33 = np.array([[1,2,3],[4,5,6]])
arr34 = np.array([[7,8,9],[10,11,12]])

# 默认情况下，沿着轴0进行拼接
arr35 = np.concatenate((arr33, arr34))
print(arr35)
print('-'*20)

# 指定轴了之后，按轴1拼接
print(np.concatenate((arr33, arr34), axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## 按哪个轴堆叠，就会增加一个维度，对应维度的size是数组的个数

In [35]:
import numpy as np
a = np.array([1, 2, 3])  # shape: (3,)
b = np.array([4, 5, 6])  # shape: (3,)
c= np.array([7, 8, 9])
# axis = 0，沿着0轴进行堆叠
np.stack([a, b, c], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.stack([a, b], axis=-1).shape

(3, 2)

In [37]:
# 二维数组的堆叠
a = np.arange(12).reshape(3, 4)
b = np.arange(12,24).reshape(3, 4)


# axis = 0，沿着0轴进行堆叠, （新轴在第0位，长度=2）
np.stack([a, b], axis=0).shape

(2, 3, 4)

In [38]:
np.stack([a, b], axis=1).shape

(3, 2, 4)

In [39]:
np.stack([a, b], axis=2).shape

(3, 4, 2)

In [40]:
# split使用
arr36 = np.arange(1, 10).reshape(3, 3)
print(arr36)

# 1. 默认情况下，按轴0进行分割
# 3表示分割成3份
arr37 = np.split(arr36, 3)
print(arr37)
print(type(arr37))

# 2. 按轴1进行分割
arr38 = np.split(arr36, 3, axis=1)
print(arr38)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
<class 'list'>
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


# 7.5 数组转置

In [45]:
arr39 = np.arange(0, 12).reshape(3, 4)
print("原始数组:")
print(arr39)

# 1. 转置第一种方式
arr40 = arr39.T
print("转置第一种方式:")
print(arr40)

# 2. 转置第二种方式
arr41 = np.transpose(arr39)
print("转置第二种方式:")
print(arr41)



原始数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
转置第一种方式:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
转置第二种方式:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [46]:
# 3. 对换数组的轴
arr42 = np.transpose(arr39)
print("对换轴:")
print(arr42)

对换轴:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [42]:
# 4. 轴滚动
# 表示把1轴滚动到0轴的位置
arr43 = np.rollaxis(arr39, 1, 0)
print("轴滚动:")
print(arr43.shape)


轴滚动:
(4, 3)


In [49]:
# 轴滚动第二个案例
arr44 = np.ones((3, 4, 5, 6))
print(arr44.shape)
# # 表示把3轴滚动到1轴的位置
arr45 = np.rollaxis(arr44, 3, 1)
print(arr45.shape)

(3, 4, 5, 6)
(3, 6, 4, 5)
